Document: fcitx5-demo
Title: Debian fcitx5-demo Manual
Author: <insert document author here>
Abstract: This manual describes what fcitx5-demo is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/fcitx5-demo/fcitx5-demo.sgml.gz

Format: postscript
Files: /usr/share/doc/fcitx5-demo/fcitx5-demo.ps.gz

Format: text
Files: /usr/share/doc/fcitx5-demo/fcitx5-demo.text.gz

Format: HTML
Index: /usr/share/doc/fcitx5-demo/html/index.html
Files: /usr/share/doc/fcitx5-demo/html/*.html
